import asyncio, json, time
from playwright.async_api import async_playwright
import pathlib as _pl
HERE = _pl.Path(__file__).resolve().parent
URL = (HERE.parent / 'index.html').as_uri()
ARGS = ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']
results = []
def ok(name, cond, extra=''):
    results.append((name, bool(cond), extra)); print(('PASS ' if cond else 'FAIL ') + name + (f'  [{extra}]' if extra else ''))
INSTR = """() => { const a = window.__nekoApp; if (a.__instr) return; a.__instr = true; window.__meows = []; window.__poses = [];
  const orig = a.audio.playMeow.bind(a.audio);
  a.audio.playMeow = (o) => { const r = orig(o); if (r) window.__meows.push({t: a.audio.ctx.currentTime + r.delay, dur: r.duration, gain: o.gain, wall: Date.now()}); return r; };
  setInterval(() => { const b = a.behavior; const n = a.now(); const m = b.mouthAt(n); window.__poses.push(m > 0.3 ? 'meow' : (twAwake(b, n) > 0.5 ? 'cuddle' : 'sleep')); }, 40); function twAwake(b, n){ return b.renderState(n).awake; } }"""
async def ev(page, js): return await page.evaluate(js)
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(args=ARGS + ['--autoplay-policy=no-user-gesture-required'])
        ctx = await b.new_context(viewport={'width':1280,'height':800}, locale='ja-JP', timezone_id='Asia/Tokyo')
        page = await ctx.new_page(); await page.route('**/fonts.googleapis.com/**', lambda r: r.abort())
        errs=[]; page.on('pageerror', lambda e: errs.append(str(e)))
        await page.goto(URL); await page.wait_for_timeout(1200)
        ok('initial audio state is none', await ev(page, "window.__nekoApp.audio.state") == 'none')
        ok('readiness idle', await ev(page, "document.getElementById('readiness').dataset.level") == 'idle')
        # --- 音を試す ---
        await page.click('#testSoundBtn'); await page.wait_for_timeout(400)
        await ev(page, INSTR)
        ok('audio running after 音を試す', await ev(page, "window.__nekoApp.audio.running"))
        ok('purr playing during sound test', await ev(page, "window.__nekoApp.audio.purrPlaying"))
        await page.wait_for_timeout(1400)
        ok('meow pose shown during test', 'meow' in await ev(page, "window.__poses"))
        await page.wait_for_timeout(3000)
        ok('sound test auto-ended (purr stopped, no session)', not await ev(page, "window.__nekoApp.audio.purrPlaying") and not await ev(page, "window.__nekoApp.session"))
        ok('sound test did not arm alarm', await ev(page, "window.__nekoApp.alarm.targetAt") is None)
        # --- 10秒後に試す ---
        await ev(page, "window.__meows.length = 0; window.__poses.length = 0")
        await page.click('#test10Btn'); await page.wait_for_timeout(500)
        ok('session started by 10s test', await ev(page, "window.__nekoApp.session"))
        sub = await ev(page, "document.getElementById('clockSub').textContent"); ok('clock shows test countdown', 'テスト' in sub, sub)
        await page.wait_for_timeout(10200)
        ok('ringing after 10s', await ev(page, "!!window.__nekoApp.alarm.ringing"))
        ok('alarm sheet visible', await ev(page, "!document.getElementById('alarmSheet').hidden"))
        ok('behavior in alarm mode', await ev(page, "window.__nekoApp.behavior.mode") == 'alarm')
        await page.wait_for_timeout(1500)
        await page.screenshot(path=str(HERE / 'out_ring_desktop.png'))
        await page.wait_for_timeout(6500)
        m = await ev(page, "window.__meows")
        overlap = [i for i in range(1,len(m)) if m[i]['t'] < m[i-1]['t'] + m[i-1]['dur'] - 0.005]
        ok('several meows played', len(m) >= 3, f'{len(m)} meows')
        ok('meows never overlap', not overlap, str(overlap))
        ok('volume ramps up', all(m[i]['gain'] >= m[i-1]['gain'] for i in range(1,len(m))) and m[-1]['gain'] > m[0]['gain'], ', '.join(f"{x['gain']:.2f}" for x in m))
        poses = await ev(page, "window.__poses")
        ok('meow and cuddle poses alternate during ring', ('meow' in poses or 'meow2' in poses) and 'cuddle' in poses)
        ok('purr ducked during alarm', await ev(page, "window.__nekoApp.audio.purrDuck.gain.value") < 0.5)
        # double start guard
        await ev(page, "window.__nekoApp.ringer.start(); window.__nekoApp.alarm.check(); window.__nekoApp.onRing && 0")
        ok('ringer has a single loop (timers<=3)', await ev(page, "window.__nekoApp.ringer.timers.length") <= 3, str(await ev(page, "window.__nekoApp.ringer.timers.length")))
        # --- 起きたよ ---
        await page.click('#wakeBtn'); await page.wait_for_timeout(300)
        n0 = len(await ev(page, "window.__meows"))
        ok('sheet hidden after 起きたよ', await ev(page, "document.getElementById('alarmSheet').hidden"))
        ok('ringer stopped', not await ev(page, "window.__nekoApp.ringer.active") and await ev(page, "window.__nekoApp.alarm.ringing") is None)
        await page.wait_for_timeout(3000)
        ok('no meows after 起きたよ', len(await ev(page, "window.__meows")) == n0)
        ok('cat calms down after wake (not in alarm mode)', await ev(page, "window.__nekoApp.behavior.mode") != 'alarm')
        ok('purr restored', await ev(page, "window.__nekoApp.audio.purrDuck.gain.value") > 0.9)
        # --- あと5分 ---
        await ev(page, "window.__nekoApp.alarm.testAt = Date.now() + 300"); await page.wait_for_timeout(1500)
        ok('rings again (test)', await ev(page, "!!window.__nekoApp.alarm.ringing"))
        await page.click('#snoozeBtn'); await page.wait_for_timeout(200)
        d = await ev(page, "window.__nekoApp.alarm.snoozeAt - Date.now()")
        ok('snooze set to ~5min', 295000 < d <= 300000, f'{d} ms')
        ok('status pill スヌーズ中', await ev(page, "document.getElementById('stAlarm').textContent") == 'スヌーズ中')
        n1 = len(await ev(page, "window.__meows")); await page.wait_for_timeout(2500)
        ok('silent during snooze', len(await ev(page, "window.__meows")) == n1)
        await ev(page, "window.__nekoApp.alarm.snoozeAt = Date.now() + 300"); await page.wait_for_timeout(1500)
        ok('snooze re-rings', (await ev(page, "window.__nekoApp.alarm.ringing && window.__nekoApp.alarm.ringing.source")) == 'snooze')
        # --- 解除 during ringing ---
        await page.click('#sheetCancelBtn'); await page.wait_for_timeout(300)
        n2 = len(await ev(page, "window.__meows")); await page.wait_for_timeout(2500)
        ok('解除 stops ring and clears', await ev(page, "window.__nekoApp.alarm.ringing") is None and await ev(page, "window.__nekoApp.alarm.snoozeAt") is None and len(await ev(page, "window.__meows")) == n2)
        # --- real alarm arming / date preview ---
        hm_future = await ev(page, "(() => { const d = new Date(Date.now() + 3*60000); return String(d.getHours()).padStart(2,'0') + ':' + String(d.getMinutes()).padStart(2,'0'); })()")
        await page.fill('#alarmTime', hm_future); await page.dispatch_event('#alarmTime', 'change')
        prev = await ev(page, "document.getElementById('timePreview').textContent"); ok('future time → 今日 preview (or 明日 near midnight)', ('今日' in prev) or ('明日' in prev), prev)
        await page.click('#armBtn'); await page.wait_for_timeout(100)
        ta = await ev(page, "window.__nekoApp.alarm.targetAt - Date.now()")
        ok('armed for the next occurrence (~2-3 min)', 60000 < ta <= 180000, f'{ta} ms')
        hm_past = await ev(page, "(() => { const d = new Date(Date.now() - 5*60000); return String(d.getHours()).padStart(2,'0') + ':' + String(d.getMinutes()).padStart(2,'0'); })()")
        await page.fill('#alarmTime', hm_past); await page.dispatch_event('#alarmTime', 'change')
        prev = await ev(page, "document.getElementById('timePreview').textContent"); ok('past time → 明日 with explicit date before setting', '明日' in prev and '変更後' in prev, prev)
        await page.click('#armBtn')
        ta = await ev(page, "window.__nekoApp.alarm.targetAt - Date.now()")
        ok('past time armed for tomorrow (~23h55m)', 23*3600e3 < ta < 24*3600e3, f'{ta/3600e3:.2f} h')
        # --- late ring when returning to the tab ---
        await ev(page, "window.__nekoApp.alarm.targetAt = Date.now() - 70000; document.dispatchEvent(new Event('visibilitychange'))")
        await page.wait_for_timeout(300)
        late = await ev(page, "document.getElementById('alarmLate').hidden ? '' : document.getElementById('alarmLate').textContent")
        ok('late notice shown on return', '遅れて' in late, late)
        ok('late ring consumed the one-shot alarm', await ev(page, "window.__nekoApp.alarm.targetAt") is None)
        await page.click('#wakeBtn'); await page.wait_for_timeout(200)
        ok('not re-armed automatically after 起きたよ', await ev(page, "window.__nekoApp.alarm.targetAt") is None and await ev(page, "document.getElementById('stAlarm').textContent") == '未セット')
        # --- reload restore ---
        await page.fill('#alarmTime', hm_future); await page.dispatch_event('#alarmTime', 'change'); await page.click('#armBtn')
        ok('session flag saved', await ev(page, "JSON.parse(localStorage.getItem('soine-neko-alarm/v1')).session") is True)
        await page.reload(); await page.wait_for_timeout(1500)
        ok('resume box shown after reload', await ev(page, "!document.getElementById('resumeBox').hidden"))
        ok('audio shows 停止中 after reload', await ev(page, "document.getElementById('stAudio').textContent") == '停止中')
        rd = await ev(page, "[document.getElementById('readiness').dataset.level, document.getElementById('readinessText').textContent]")
        ok('readiness warns (not shown as running)', rd[0] == 'bad', rd[1])
        al = await ev(page, "[document.getElementById('stAlarm').textContent, document.getElementById('stAlarm').dataset.level, document.getElementById('stAlarmText').textContent]")
        ok('alarm restored but flagged as silent', al[0] == '有効' and al[1] == 'warn' and '鳴りません' in al[2], ' / '.join(al))
        await page.click('#resumeBtn'); await page.wait_for_timeout(800)
        ok('resume → audio running + purr', await ev(page, "window.__nekoApp.audio.running && window.__nekoApp.audio.purrPlaying"))
        ok('resume box hidden', await ev(page, "document.getElementById('resumeBox').hidden"))
        ok('readiness ok after resume', await ev(page, "document.getElementById('readiness').dataset.level") == 'ok')
        # --- missed alarm while closed ---
        await ev(page, "(() => { const s = JSON.parse(localStorage.getItem('soine-neko-alarm/v1')); s.targetAt = Date.now() - 10*60000; localStorage.setItem('soine-neko-alarm/v1', JSON.stringify(s)); })()")
        await page.reload(); await page.wait_for_timeout(1500)
        t = await ev(page, "document.getElementById('toast').hidden ? '' : document.getElementById('toast').textContent")
        ok('missed alarm is reported, not rung', '鳴らせませんでした' in t and await ev(page, "window.__nekoApp.alarm.ringing") is None, t)
        # --- tap on cat vs elsewhere ---
        await ev(page, "document.getElementById('resumeEndBtn').click()")
        box = await ev(page, "(() => { const a = window.__nekoApp; const r = a.sceneEl.getBoundingClientRect(); const pts=[]; for (let y=r.top+10;y<r.bottom;y+=12) for (let x=r.left+10;x<r.right;x+=12) if (a.hitCat(x,y)) pts.push([x,y]); return pts[Math.floor(pts.length/2)]; })()")
        await page.mouse.click(box[0], box[1]); await page.wait_for_timeout(300)
        ok('tapping the cat triggers a short reaction', await ev(page, "window.__nekoApp.behavior.action") == 'react')
        ok('tap did not touch alarm', await ev(page, "window.__nekoApp.alarm.ringing") is None)
        ok('no page errors', not errs, '; '.join(errs))
        await ctx.close()

        # ===== Context B: no autoplay permission → audio blocked until tap =====
        b2 = await p.chromium.launch(args=ARGS)
        ctx = await b2.new_context(viewport={'width':390,'height':844}, device_scale_factor=2, is_mobile=True, has_touch=True, locale='ja-JP', timezone_id='Asia/Tokyo')
        page = await ctx.new_page(); await page.route('**/fonts.googleapis.com/**', lambda r: r.abort()); errs=[]; page.on('pageerror', lambda e: errs.append(str(e)))
        await page.goto(URL); await page.wait_for_timeout(1200)
        await ev(page, "window.__nekoApp.alarm.testAt = Date.now() + 500"); await page.wait_for_timeout(1800)
        ok('[no audio] rings visually', await ev(page, "!!window.__nekoApp.alarm.ringing"))
        ok('[no audio] warns 音が出ていません', await ev(page, "!document.getElementById('alarmAudio').hidden"))
        await page.screenshot(path=str(HERE / 'out_ring_mobile_noaudio.png'))
        await page.tap('#alarmAudioBtn'); await page.wait_for_timeout(3500)
        ok('[no audio] tap → audio running', await ev(page, "window.__nekoApp.audio.running"))
        ok('[no audio] warning cleared after sound resumes', await ev(page, "document.getElementById('alarmAudio').hidden"))
        await page.screenshot(path=str(HERE / 'out_ring_mobile.png'))
        await page.tap('#wakeBtn'); await page.wait_for_timeout(300)
        ok('[mobile] no page errors', not errs, '; '.join(errs))
        await ctx.close(); await b2.close()

        # ===== Context C: fake clock across the year boundary =====
        ctx = await b.new_context(viewport={'width':1280,'height':800}, locale='ja-JP', timezone_id='Asia/Tokyo')
        page = await ctx.new_page(); await page.route('**/fonts.googleapis.com/**', lambda r: r.abort()); errs=[]; page.on('pageerror', lambda e: errs.append(str(e)))
        await page.clock.install(time='2026-12-31T23:50:00+09:00')
        await page.goto(URL); await page.clock.run_for(1500)
        await page.fill('#alarmTime', '00:05'); await page.dispatch_event('#alarmTime', 'change')
        prev = await ev(page, "document.getElementById('timePreview').textContent")
        ok('[clock] 23:50 → 00:05 is 明日 1月1日(金)', '明日' in prev and '1月1日(金)' in prev and '0:05' in prev, prev)
        await page.click('#armBtn')
        tgt = await ev(page, "new Date(window.__nekoApp.alarm.targetAt).toString()")
        ok('[clock] target is 2027-01-01 00:05 local', 'Jan 01 2027 00:05' in tgt, tgt)
        await page.fill('#alarmTime', '23:50'); await page.dispatch_event('#alarmTime', 'change')
        prev = await ev(page, "document.getElementById('timePreview').textContent")
        ok('[clock] same minute as now → tomorrow', '明日' in prev and '1月1日' in prev, prev)
        await page.fill('#alarmTime', '00:05'); await page.dispatch_event('#alarmTime', 'change')
        await page.clock.fast_forward('10:00'); await page.clock.run_for(1500)
        ok('[clock] not ringing before target', await ev(page, "window.__nekoApp.alarm.ringing") is None)
        await page.clock.fast_forward('06:00'); await page.clock.run_for(1500)
        r = await ev(page, "window.__nekoApp.alarm.ringing")
        ok('[clock] rings after crossing midnight/new year', r is not None and r['source'] == 'alarm', json.dumps(r))
        ok('[clock] no page errors', not errs, '; '.join(errs))
        await ctx.close()
        await b.close()
    print(f"\n{sum(1 for r in results if r[1])}/{len(results)} passed")
asyncio.run(main())
